"""empty message

Revision ID: 2caf65dc673d
Revises: 51e9564d37cb
Create Date: 2016-01-15 10:21:49.317287

"""

# revision identifiers, used by Alembic.
revision = '2caf65dc673d'
down_revision = '51e9564d37cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
