"""empty message

Revision ID: 46b950b9be20
Revises: 1e1fc3825671
Create Date: 2016-01-09 06:30:55.387806

"""

# revision identifiers, used by Alembic.
revision = '46b950b9be20'
down_revision = '1e1fc3825671'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('program', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'program')
    ### end Alembic commands ###
