"""empty message

Revision ID: 50abf8cc7a7b
Revises: 1e1fc3825671
Create Date: 2016-01-19 00:33:09.594652

"""

# revision identifiers, used by Alembic.
revision = '50abf8cc7a7b'
down_revision = '1e1fc3825671'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('program', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'program')
    ### end Alembic commands ###
