"""empty message

Revision ID: 51e9564d37cb
Revises: 46b950b9be20
Create Date: 2016-01-15 06:00:58.366831

"""

# revision identifiers, used by Alembic.
revision = '51e9564d37cb'
down_revision = '46b950b9be20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
